// GLSL Vertex Shader "vertex_main"
// Generated by XShaderCompiler
// 16/08/2018 23:04:15

#version 330

in vec3 position;
in vec2 texcoord;

layout(std140, row_major) uniform PerObject
{
    mat4 model;
    mat4 normal_matrix;
};

layout(std140, row_major) uniform PerView
{
    mat4 view_projection;
    vec2 viewport_dimensions;
};

void main()
{
    gl_Position = ((view_projection * model) * vec4(position, 1.0));
}

