// GLSL Fragment Shader "pixel_main"
// Generated by XShaderCompiler
// 21/08/2018 16:48:12

#version 330

layout(location = 0) out vec4 SV_Target0;

layout(std140) uniform HaloBlock
{
    vec4 halo_colour;
};

void main()
{
    SV_Target0 = halo_colour;
}

