// GLSL Vertex Shader "vertex_main"
// Generated by XShaderCompiler
// 16/08/2018 23:04:15

#version 330

in vec3 position;
in vec2 texcoord;

out vec2 xsv_TEXCOORD0;

layout(std140, row_major) uniform PerView
{
    mat4 view_projection;
    vec2 viewport_dimensions;
};

void main()
{
    gl_Position = (view_projection * vec4(position, 1.0));
    xsv_TEXCOORD0 = texcoord;
}

