// GLSL Fragment Shader "pixel_main"
// Generated by XShaderCompiler
// 16/08/2018 23:04:15

#version 330

in vec3 xsv_NORMAL0;
in vec3 xsv_COLOR0;

layout(location = 0) out vec4 SV_Target0;

layout(std140) uniform LightBlock
{
    vec3 light_direction;
};

float half_lambert(vec3 n, vec3 l)
{
    return 0.5f * dot(n, l) + 0.5f;
}

void main()
{
    float light = half_lambert(xsv_NORMAL0, light_direction);
    SV_Target0 = vec4(xsv_COLOR0 * vec3(light), 1.0);
}

