// GLSL Fragment Shader "pixel_main"
// Generated by XShaderCompiler
// 23/08/2018 15:37:34

#version 330

              in vec4 xsv_COLOR0;
noperspective in vec2 xsv_TEXCOORD0;

layout(location = 0) out vec4 SV_Target0;

uniform sampler2D texture0;

float cutoff = 0.3f;

void main()
{
    vec4 texture_colour = texture(texture0, xsv_TEXCOORD0);
    if (texture_colour.a < cutoff)
        discard;
    SV_Target0 = xsv_COLOR0 * texture_colour;
}

