// GLSL Fragment Shader "pixel_main"
// Generated by XShaderCompiler
// 16/08/2018 23:04:15

#version 330

in vec3 xsv_TEXCOORD0;
in vec4 xsv_COLOR0;

layout(location = 0) out vec4 SV_Target0;

uniform sampler2D texture0;

void main()
{
    vec2 screen_texcoord = xsv_TEXCOORD0.xy / xsv_TEXCOORD0.z;
    SV_Target0 = xsv_COLOR0 * texture(texture0, screen_texcoord);
}

