// GLSL Fragment Shader "pixel_main"
// Generated by XShaderCompiler
// 23/08/2018 15:37:34

#version 330

in vec4 xsv_COLOR0;

layout(location = 0) out vec4 SV_Target0;

void main()
{
    SV_Target0 = xsv_COLOR0;
}

